name: Solve Pip Requirements

on:
  workflow_dispatch:

jobs:
  solve:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py_version: [8, 9, 10, 11, 12]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.${{ matrix.py_version }}'

    - run: |
        pip install uv
        uv pip install -r dev_requirements_py3${{ matrix.py_version }}.txt
        PYTHONPATH=$(pwd) python test/symforce_requirements_test.py --update --piptools_upgrade

    - uses: actions/upload-artifact@v4
      with:
        path: dev_requirements_py3${{ matrix.py_version }}.txt

  publish:
    runs-on: ubuntu-latest
    needs: solve
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update Requirements
        title: Update Requirements
        body: ""